version: "3.9"

services: 

  fast_heroes:
    depends_on:
      - postgres
    container_name: hero_app
    build: 
      context: ./hero-app/
      dockerfile: Dockerfile
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    # environment:
    #   - CONTAINER_PORT=${CONTAINER_PORT}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - DB_SERVICE_NAME=${DB_SERVICE_NAME}
    #   - DB_SERVICE_PORT=${DB_SERVICE_PORT}
    env_file:
      - .env

  postgres: # this should be DB_SERVICE_NAME
    container_name: database
    image: postgres
    volumes: 
    - type: volume
      source: postgres-vol
      target: /var/lib/postgresql/data
    environment: 
      # by default these variables will be fetched from .env file
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-vol: {}
  