[tool.black]
line-length = 90
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  \.git
  |\.sh
  |\.ini
  |Dockerfile
  |Jenkinfile
)/
'''

[tool.isort]
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
known_third_party = ["api", "app", "base", "django", "fastapi", "mlflow", "models", "movies", "numpy", "pandas", "phonebook", "player_classes", "pytest", "sklearn", "sqlmodel", "starlette", "tastypie", "uvicorn"]
profile = "black"
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
ensure_newline_before_comments = "True"
line_length = 90
