version: "3.9"

services:
  mysql-db:
    # image: mysql:5.7
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      # - MYSQL_DATABASE=default_db
      # - MYSQL_USER=default_user
      # - MYSQL_PASSWORD=secret
    volumes:
      - ./data:/var/lib/mysql
      # - ./scripts:/local-scripts
      - ./scripts:/docker-entrypoint-initdb.d
